### ISSUE TITLE
rex_ynewsletter_log erweitern (ErrorInfo)

### ISSUE THREAD

**Issue by MC-PMOE** [yakamara/redaxo_ynewsletter#13]
Vielleicht könnte man $mail->ErrorInfo in einem weiteren Feld im Log mit hinterlegen?
Oder im Systemlog mit ausgeben?

**Comment by dergel** [comment]
warten wir die redaxo 5.9 version ab, wie phpmailer loggt und damit wäre es vielleicht auch schon wesentlich verbessert.

**Comment by dergel** [comment]
Ab den neuen REDAXO Version kann man eigene Logs reinhängen, dass wäre hier noch ein ToDo

**Comment by dergel** [comment]
Mittlerweile gibt es einen eigenen phpmailer log. d.h. dort werden die Fehler geloggt.
