### ISSUE TITLE
Abmeldefunktion!?

### ISSUE THREAD

**Issue by HassChristian** [yakamara/redaxo_ynewsletter#14]
Es wäre toll wenn es noch eine Abmeldefunktion in der Beschreibung gebe. ;-) 

Gruß Christian :-)

**Comment by alexplusde** [comment]
Hey @HassChristian, möchtest du die Doku dahingehend ergänzen? Sollte nicht schwer sein. Mit rex_sql den status verändern.

**Comment by dergel** [comment]
Eigentlich ist das nicht der Part von ynewsletter, weil es kein Usermanagement macht oder entscheidet wer welchen Newsletter unter welchen Umständen bekommt. Das kann man ja individuell festlegen. Aber ich finde, man könnte sowas wie ein Abmeldepool erstellen. So dass, falls jemand sich von einem Newsletter abmeldet, er genau diesen einen nicht mehr bekommt.  D.h. er würde aus einer Gruppe ausgeschlossen werden können.

**Comment by erraiva** [comment]
vom Newsletter abmelden geht bei mir so:
Artikel für die Abmeldung erzeugen und dieses Formular einsetzen (status ist hier nur andersherum wie bei der Anmeldung)

```
hidden|status|0
hidden|newsletter|1
objparams|submit_btn_show|0
objparams|send|1
objparams|csrf_protection|0

validate|ynewsletter_auth|%TABLE%|activation_key=activation_key,email=email|status=1|{{ form.newsletter.error.confirmation.validate }}|

action|db|%TABLE%|main_where

```
im Modul für den NL-Inhalt den Unsubscribe-Link erzeugen und im Footer des NL einsetzen:

```
$unsubscribelink = rex::getServer().rex_getUrl(%ARTICLE_ID_UNSUBSCRIBE%).'?activationkey=REX_YNEWSLETTER_DATA[field="activationkey"]&email=REX_YNEWSLETTER_DATA[field="email"]';
$unsubscribelink = str_replace(['.de//'],['.de/'],$unsubscribelink);
```

Wobei auch hier %TABLE% und %ARTICLE_ID_UNSUBSCRIBE% ersetzt werden müssen
Das str_replace gilt für .de Domains, bei anderen TLDs bitten entsprechend ändern.
Grüße von Heinz

**Comment by HassChristian** [comment]
Hey, danke für die Antwort. Hab schon gar nicht mehr damit gerechnet.

Mir ging es um das Recht auf Lösung meiner Daten, anstatt den User auf inaktiv zu setzen. Solange ich von meinem Newsletter Anbieter wegkomme ist mir das egal. 

@alexplusde Ich würde mir wünschen, das ich irgendwo noch ein paar Tutorials finde die mir den Umgang mit Yform noch erleichtern. So im Moment wäre ich keine große Hilfe weil ich wohl mehr Fragen wie Antworten hätte. :-) Später vielleicht gern. ;-)

@erraiva Danke dir. Ich werde es nächste Woche einbauen und testen.

Have a nice Day! Christian :-)
