### ISSUE TITLE
Sprachabhängigen Versand ermöglichen.

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ynewsletter#17]
Userlisten kennzeichnen können um festzulegen, welche Sprachvariante an wen geschickt werden soll.

**Comment by tyrant88** [comment]
Ist eigentlich auch so schon gut machbar:

1) Das "subject" muss auch übersetzt werden und auch eine andere Absenderadresse kann vorkommen, also muss man eh einen weiteren Newsletter anlegen.

2) Dann kann man auch die verschiedene Empfängergruppen nutzen. Die kann man ganz flexibel über die Filter bilden ( WHERE lang = "englisch" ) oder noch raffinierter (WHERE country IN ( 'de,ch,at') ).
 Das Gute: man muss niemandem vorschreiben wie die Tabelllenfelder bzw. die Sprachzuordnung aussieht.

3) Jetzt müsste man die verschiedenen Sprachen als verschiedene Artikel in der ersten Sprache anlegen und dann auswählen.
Dafür mache ich jetzt noch einen PR, der ein Sprach-Select in die Newsletter-Tabelle hinzufügt. Damit wird dann die entsprechende Sprachversion des ausgewählten Artikel genutzt.

**Comment by dergel** [comment]
Hast Recht .. eigentlich braucht man nun einen Sprachauswahl für den Artikel .. top .. gerne PR

**Comment by tyrant88** [comment]
PR hatte ich schon gemacht.
