### ISSUE TITLE
Testmail vereinfachen.

### ISSUE THREAD

**Issue by dergel** [yakamara/redaxo_ynewsletter#2]

**Comment by tbaddade** [comment]
Eventuell wieder mit der Checkbox "Testversand" und das Eintragen einer eigenen E-Mail-Adresse

Aktuell muss man 
- eine separate Gruppe anlegen
- den Newsletterstatus wieder auf "offen" stellen
- den Logeintrag des Testversands löschen oder einen neuen Newsletter anlegen

**Comment by dergel** [comment]
Eigentlich reicht das so.. Haben das mehrfach so gemacht und klappt gut
