### ISSUE TITLE
Das verschicken eines leeren Artikels für zu Probleme 

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ynewsletter#22]
Wenn man einen leeren Artikel (=kein slice) verschickt um z.b. bei der Entwicklung das Template zu testen dann wird im E-Mail Client der HTML Quellcode angezeigt...

**Comment by tyrant88** [comment]
Der PHP Mailer setzt den message type auf "plain", wenn der altBody des Mail-Objekts leer ist. 
Bei Plain wird einfach der Body eingefügt ohne Mime.Kennzeichnung als HTML. 
Deshalb sieht das dann so aus. HTML als plain angezeigt.

Der Fix ist ziemlich mies. Aber ich habe keine andere Lösung gefunden, so wie der PHPMailer das macht. (Er prüft beim zusammenbauen der Mail, ob der altBody leer ist... da kommt man nicht mehr ran)
