### ISSUE TITLE
Ersetzung "greift" nicht

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ynewsletter#23]
![image](https://user-images.githubusercontent.com/330516/96114641-2e7ad180-0ee6-11eb-9b7a-b6d1792328f5.png)

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/96114674-389cd000-0ee6-11eb-9476-95f39c7b93f7.png)

**Comment by tyrant88** [comment]
WO soll das denn sein?

**Comment by olien** [comment]
Sorry. Hier:

/redaxo/index.php?page=ynewsletter/newsletter

**Comment by dergel** [comment]
Bei mir sieht es so aus:
<img width="227" alt="Bildschirmfoto 2020-10-16 um 09 47 39" src="https://user-images.githubusercontent.com/322951/96227832-fa121e80-0f94-11eb-8354-0900b7380620.png">

**Comment by olien** [comment]
![image](https://user-images.githubusercontent.com/330516/96228442-e74c1980-0f95-11eb-915f-1f2ef6f40bcb.png)

**Comment by tyrant88** [comment]
Häh? "Duplizieren?" noch zweimal "status"?

**Comment by dergel** [comment]
@olien ping.. das hast du was eigenes drin, oder ?

**Comment by olien** [comment]
Ne. So aus dem installer...

**Comment by tyrant88** [comment]
Drück mal auf reinstallieren...

**Comment by olien** [comment]
Frühestens Montag. Rechner ist aus ;-))))) (Sorry)

**Comment by olien** [comment]
Ok. Es kollidiert mit dem yform_usability AddOn. Das Statusfeld wird angezeigt (trotzdem müsste doch die Übersetzung greifen - oder?)

**Comment by dergel** [comment]
keine Ahnung .. leider weiss ich nicht wie das yform_usability AddOn funktioniert.. wenn du es deaktivierst geht wieder alles ? Wenn ja, dann bei yform_usability ein Issue aufmachen und das hier schliessen.

**Comment by olien** [comment]
Kann hier zu. Danke fürs gucken!
