### ISSUE TITLE
Funktioniert es?

### ISSUE THREAD

**Issue by phoebusryan** [yakamara/redaxo_ynewsletter#3]
An sich ein tolles Addon und ich freu mich drauf. Ich wollte es aber gerade mal einsetzen/testen und musste feststellen, dass es irgendwie nicht funktioniert oder ich zu blöd bin :).

Ich habe schon länger eine yform-Tabelle 'rex_newsletter_subscribers' und nun das Addon installiert. Dann habe ich eine Gruppe angelegt. Tabellenname ist 'rex_newsletter_subscribers'; E-Mail Feld ist 'email'. 

Anschliessend bin ich auf Newsletter gegangen und habe dort einen angelegt. Beim Versand kommt aber lediglich die Meldung `Error while executing statement "select * from ``"! SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''` ... und das obwohl beim Newsletter eine Gruppe hinterlegt ist.

**Comment by dergel** [comment]
"eigentlich" geht es .. und wir verwenden esja auch .. hast du bei der gruppeneinstellung auch wirklich eine Tabelle eingetragen ? einfach mal eine neue Gruppe aufmachen ?

Es kann jede Tabelle genutzt werden. Einschränkt wird der Gruppenversand nur über die Filter.. pro Zeile das entsprechend SQL Statement setzen. z.B.

```
status=1
newsletter=1
```

**Comment by phoebusryan** [comment]
Ja natürlich habe ich eine Tabelle angelegt. Filter brauche ich nicht, weil es ja eine allgemeine Liste für Abonnenten ist. Kannst du mich morgen mal in Slack anschreiben?

**Comment by dergel** [comment]
hmm.. ich überlege gerade .. kannst du schauen ob die tabelle auch als yform anleget ist ? wenn nicht, könnte es das bereits erklären, und müsste entsprechend von mir dort gefiltert und kommentiert werden.

**Comment by phoebusryan** [comment]
Die Tabelle wurde via yform angelegt.

**Comment by phoebusryan** [comment]
Liegt an der yform-Beta-Version gemäss debugging von @dergel

**Comment by dergel** [comment]
nicht mit der yform 2.3b benutzen.. mit yform 2.4 wirds auch wieder gehen- und mit 2.2 ging es (glaube ich) auch..
