### ISSUE TITLE
clang notice beim Testversand 

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ynewsletter#30]
Alles ist aktuell (Installer).
Zwei Sprachen sind eingerichtet 

![image](https://user-images.githubusercontent.com/330516/99394904-f8af7b00-28df-11eb-93fa-cc56e8cab611.png)

**Comment by dergel** [comment]
ich kann es leider nicht nachvollziehen. 
Kannst du das AddOn neu installieren und geht es dann ? Reinstall sollte auch gehen
