### ISSUE TITLE
Beispiele deaktivieren CSRF-Token. Ist das so gewollt?

### ISSUE THREAD

**Issue by alxndr-w** [yakamara/redaxo_ynewsletter#31]
https://github.com/yakamara/redaxo_ynewsletter/blob/master/README.md#anmeldung-best%C3%A4tigen

Wenn ja: Warum?

**Comment by dergel** [comment]
ja, weil es eine direkte bestätigung (Link aus der E-Mail) ist und das Formular nicht erst noch abgeschickt werden soll.

**Comment by alxndr-w** [comment]
Danke für die Auskunft.
