### ISSUE TITLE
GitHub Adresse falsch, Fehlermeldung

### ISSUE THREAD

**Issue by abra100pro** [yakamara/redaxo_ynewsletter#46]
Auch hier ist die GitHub-Adresse falsch in der add-on-Hilfe: Es steht dort github.org anstatt github.com

Ich kann ynewsletter mit yform 4.0.0 nicht installieren (Versionsfehlermeldung). Daraufhin habe ich im packages.yml die Version manuell auf 4 gesetzt. Die Installation geht, aber wenn ich dann im Modul bspw. auf den Tab "Versand" klicke, kommt dies:

Error while executing statement "SELECT `rex_ynewsletter`.* FROM `rex_ynewsletter` WHERE `status` = :p1 ORDER BY `id` desc" using params {"p1":0}! SQLSTATE[42S22]: Column not found: 1054 Unknown column 'status' in 'where clause'

**Comment by dergel** [comment]
das sollte hiermit passen. Beim nächsten Release ist es drin
