### ISSUE TITLE
Personalierte Newsletter ermöglichen

### ISSUE THREAD

**Issue by phoebusryan** [yakamara/redaxo_ynewsletter#5]
Ich würde gerne einen personalisierten Newsletter verschicken. Sprich mit Platzhaltern für Vorname/Nachname. Diese müsste man irgendwie definieren können, PR dafür steht bereit.

**Comment by dergel** [comment]
leider nicht so wie der PR, sondern wie in der YFORm bei den E-Mail-templates war mein Plan. D.h. man kann Platzhalter dann in etwas so setzen .. REX_USER_DATA[field="name" ifempty="Mein Name"] ...

**Comment by dergel** [comment]
REX_YNEWSLETTER_DATA[field="email"] .. das ist nun drin .
