### ISSUE TITLE
Ist feststellbar welche Mails nicht zugestellt werden konnten (Bounce)

### ISSUE THREAD

**Issue by olien** [yakamara/redaxo_ynewsletter#54]
Könne man das ggf. gegen "Geld" einbauen?

**Comment by olien** [comment]
ok. probiere Mailjet

**Comment by dergel** [comment]
Wir nutzen YNewsletter mit mailjet und smtp relay.. bounces aus Mailjet werden dann über die Trigger dort im YNewsletter aufgenommen und im Log dokumentiert.
