### ISSUE TITLE
Leerzeilen entfernen

### ISSUE THREAD

**Issue by tbaddade** [yakamara/redaxo_ynewsletter#7]
https://github.com/yakamara/redaxo_ynewsletter/blob/master/lib/ynewsletter.php#L62

Übernehmen aus `yform/email`
```
    public static function makeSingleLine($str)
    {
        $str = str_replace("\n", '', $str);
        $str = str_replace("\r", '', $str);
        return $str;
    }
```

**Comment by dergel** [comment]
eher sowas wie das hier, oder ?

`preg_replace( "/[\r\n]+/", "\n", $text )`
